name: Upload to PyPi

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build_and_publish:
    name: Build and upload wheels
    permissions:
      contents: read
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      with:
        fetch-depth: 0
        fetch-tags: true

    - uses: prefix-dev/setup-pixi@a0af7a228712d6121d37aba47adf55c1332c9c2e # v0.9.4
      with:
        pixi-version: 'latest'
        locked: true
        cache: true
        cache-write: ${{ github.ref == 'refs/heads/main' }}
        environments: build

    - name: Build
      run: pixi run -e build build-wheels

    - name: Publish to PyPi
      if: startsWith(github.ref, 'refs/tags/v')
      env:
        UV_PUBLISH_TOKEN: ${{ secrets.PYPI_TOKEN }}
      run: pixi run -e build publish-pypi
